config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :flats, only: [:show, :new, :create, :destroy] do
    resources :bookings, only: [:create]
    resources :reviews, only: [:create]
  end

  resources :bookings, only: [:update, :destroy]

  get "bookings", to: "bookings#index", as: "user_bookings"
  get "flats", to: "flats#owner_index", as: "owner_flats"
  # post "create" only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    errors.add(:end_date, "must be after the start date") if end_date < start_date
  end
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_address,
    against: [ :address ],
    using: {
    tsearch: { prefix: true }
    }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :reviews, dependent: :destroy

  validates :name, :address, :description, :price, presence: true

  def unavailable_start_dates
    booked_days = []
    unavailable_date_ranges = bookings.map { |b| (b.start_date...b.end_date) }
    unavailable_date_ranges.each do |range|
      range.each { |day| booked_days << day }
    end
    return booked_days.uniq
  end

  def unavailable_end_dates
    booked_days = []
    unavailable_date_ranges = bookings.map { |b| b.start_date.next_day(1)..b.end_date }
    unavailable_date_ranges.each do |range|
      range.each { |day| booked_days << day }
    end
    return booked_days.uniq
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :flat

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: 1..5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :flats

  has_many :reviews, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @user = current_user
    @bookings = current_user.bookings
    @my_flats = current_user.flats
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.flat = Flat.find(params[:flat_id])
    @booking.user = current_user
    redirect_to user_bookings_path, notice: 'Booking was successfully created.' if @booking.save!
  end

  def update
    booking = Booking.find(params["id"])
    booking.status = params["status"]
    booking.save!
    redirect_to user_bookings_path
  end

  def destroy
    booking = Booking.find(params[:id])
    booking.destroy
    redirect_to user_bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_flat, only: [:show]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    if @flat.save
      flash[:success] = "Flat created successfully!"
      current_user.update_attribute(:owner?, true) if current_user.owner? == false
      redirect_to root_path
    else
      render :new
    end
  end

  def owner_index
    @user = current_user
    @flats = current_user.flats
  end

  def show
    @flat = Flat.find(params[:id])
    @reviews = @flat.reviews
    @booking = Booking.new
    @review = Review.new

    if @flat.geocoded?
      @markers = [{
        lat: @flat.latitude,
        lng: @flat.longitude
      }]
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :price, :description, :poster_url)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @flats = Flat.all
    user_query = params[:query]
    if user_query.present?
      @flats = @flats.search_by_address(user_query)
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @flat = Flat.find(params[:flat_id])
    @review = Review.new(review_params)
    @review.user = current_user
    @review.flat = @flat

    if @review.save
      redirect_to flat_path(@flat), notice: 'Review was successfully created.'
    else
      @booking = Booking.new
      @reviews = @flat.reviews
      render "flats/show", status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_flat_bookings.html.erb
<% user = User.find(booking.user_id) %>

<div class="card-product m-2 mx-auto" style="max-width:600px;">
  <img src="<%= my_flat.poster_url %>" />
  <div class="card-product-infos flex-grow-1">
    <p><% if user.name.nil? %>A user<% else %><%= user.name.capitalize %><% end %> wants to book your flat during <%= (booking.end_date - booking.start_date).to_i %> day(s):</p>
    <p>From : <b><%= booking.start_date.strftime('%a, %e of %B %Y') %></b> to : <b><%= booking.end_date.strftime('%a, %e of %B %Y') %></b> </p>
    <h5 class="mt-3">Status : <%= booking.status %></h5>
  </div>
  <div class="status-change">
    <% if booking.status == "pending" %>
      <%= simple_form_for(booking) do |f| %>
        <%= hidden_field_tag :status, "accepted" %>
        <%= button_tag type: 'submit', class: "booking-validation-button" do %>
          <i class="fa-solid fa-check fa-xl" style="color: #095d40;"></i>
        <% end %>
      <% end %>
      <%= simple_form_for(booking) do |f| %>
        <%= hidden_field_tag :status, "declined" %>
        <%= button_tag type: 'submit', class: "booking-validation-button" do %>
          <i class='fa-solid fa-xmark fa-xl' style='color: #8a0000;'></i>
        <% end %>
      <% end %>
    <% elsif booking.status == "accepted" %>
      <%= simple_form_for(booking) do |f| %>
        <%= hidden_field_tag :status, "declined" %>
        <%= button_tag type: 'submit', class: "booking-validation-button" do %>
          <i class='fa-solid fa-xmark fa-xl' style='color: #8a0000;'></i>
        <% end %>
      <% end %>
    <% elsif booking.status == "declined" %>
      <%= simple_form_for(booking) do |f| %>
        <%= hidden_field_tag :status, "accepted" %>
        <%= button_tag type: 'submit', class: "booking-validation-button" do %>
          <i class="fa-solid fa-check fa-xl" style="color: #095d40;"></i>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/_owner_flats.html.erb
<% bookings = Booking.where(flat_id: my_flat.id) %>
<div class="bookings-block p-4 my-3">
<h4 class="text-center my-3">Your flat: "<%= my_flat.name %>"</h4>
  <% if bookings.empty? %>
    <h5 class="text-center mt-3 text-warning">You have no booking for this flat !</h5>
  <% else %>
    <% bookings.each do |owner_booking| %>
      <%= render "flat_bookings", booking: owner_booking, my_flat: my_flat %>
    <% end %>
  <% end %>
</div>

app/views/bookings/_user_booking.html.erb
<% flat = Flat.find(booking.flat_id)%>

<div class="flat-card mb-3 position-relative">
  <div class="cancel-button-top">
    <%= link_to ("<i class='fa-solid fa-xmark fa-xl' style='color: #8a0000;'></i>").html_safe, booking_path(booking.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure to cancel your booking?"} %>
  </div>
  <%= image_tag(flat.poster_url, alt: "Flat image", class: "card-img-top") unless flat.poster_url.blank? %>
  <%= image_tag("https://th.bing.com/th/id/OIG4.tPvwVrEHahLe6Kjf4I0p?w=1024&h=1024&rs=1&pid=ImgDetMain", alt: "Default flat image", class: "card-img-top") if flat.poster_url.blank? %>
  <div class="card-body">
    <h5 class="card-title"><%= flat.name %></h5>
    <p class="card-text mb-1">Status : <%= booking.status %></p>
    <p class="card-text mb-1"><b>Check-in : <%= booking.start_date.strftime('%a, %e of %B %Y') %><br>Check-out : <%= booking.end_date.strftime('%a, %e of %B %Y') %></b></p>
    <p class="description"><%= flat.description.truncate(35, separator: ' ') %></p>
    <div class="d-flex justify-content-between">
      <%= link_to "See the flat", flat_path(flat) %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="back-button-container">
  <%= link_to :back do %>
    <%= image_tag "Back.png" %>
  <% end %></div>
<div class="flat-card-container">
<div class="container my-5 mx-auto pb-5">
<h1 class="text-center my-4">Welcome <%= @user.name unless @user.name.nil? %></h1>
<div class="my-5">
  <h2>Here are the bookings for your next trips:</h2>
  <% if @bookings.empty? %>
    <div class="bookings-block p-4 bg-light my-3">
      <h5 class="text-center mt-3 text-warning">You have nothing booked for your trips yet</h5>
    </div>
  <% else %>
    <div class="home-card-container justify-content-evenly">
      <%  @bookings.each do |booking| %>
        <div class="col-md-4 col-lg-3 mb-3">
          <%= render "user_booking", booking: booking %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="my-5">
  <% unless @my_flats.empty? %>
  <h2>Your flats are requested for these dates:</h2>
  <div class="mt-4">
    <% @my_flats.each do |my_flat| %>
      <%= render "owner_flats", my_flat: my_flat %>
    <% end %>
  </div>
<% end %>
</div>

</div>

app/views/flats/index.html.erb
<div class="container">

  <div class="row justify-content-center mt-4">
    <div class="col-sm-8 my-3">
      <%= form_with url: flats_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Type a keyword"
          %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>


  <div class="row justify-content-center">
    <div class="col-sm-8">
      <div id="movies">
        <% if @flats.any? %>
          <% @flats.each do |flats| %>
            <h4><%= flats.name %></h4>
            <p><%= flats.address %></p>
          <% end %>
        <% else %>
          <em>Sorry, no flats found.</em>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="back-button-container">
  <%= link_to :back do %>
    <%= image_tag "Back.png" %>
  <% end %></div>
<div class="flat-card-container">
<div class="new-flat-form">

  <h2>New flat</h2>

  <%= simple_form_for @flat, url: flats_path, method: :post do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :price, label: "Price per night (in €)" %>
    <%= f.input :description %>
    <%= f.input :poster_url %>

    <%= f.submit "Create Flat", class: "app-button" %>
  <% end %>

</div>

app/views/flats/owner_index.html.erb
<div class="back-button-container">
  <%= link_to :back do %>
    <%= image_tag "Back.png" %>
  <% end %></div>
<div class="flat-card-container">
<div class="container my-4">
  <h3 class="text-center my-4"><% if @user.name.nil? %>Here <% else %><%= @user.name %>, here<% end %> are all your flats: </h3>

<div>
 <% @flats.each do |flat| %>
    <div class="card-product m-2 position-relative mx-auto"  style="max-width:700px;">
      <div class="cancel-button-top">
        <%= link_to ("<i class='fa-solid fa-xmark fa-xl' style='color: #8a0000;'></i>").html_safe, flat_path(flat),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      </div>
      <img src="<%= flat.poster_url %>" />
      <div class="card-product-infos flex-grow-1">
    <p><%= link_to "See your flat", flat_path(flat.id), class: "nav-link" %></p>
        <h2><%= flat.name %></h2>
        <p><%= flat.description %></p>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/flats/show.html.erb
<div class="flat-card-container">
  <div class="flat">
    <div>
      <img
        src="<%= @flat.poster_url %>"
        class="flat-img-left"
        alt="Photo of <%= @flat.name %>"
      />
    </div>
    <div class="flat-body">
      <div>
        <br>
        <h2><%= @flat.name %></h2>
        <p><%= @flat.address %></p>
        <h3><strong> € <%= @flat.price %></strong> / night</h3>
        <p>
          <%= @flat.description %>
        </p>
        <br>
      </div>
      <div data-controller="toggle" data-contoller="flatpickr" >
        <a class="app-button" data-action="click->toggle#fire">
          📅 Choose a date
        </a>
        <div class="new-flat-form" data-toggle-target="togglableElement" >
        <%= simple_form_for([@flat, @booking]) do |f| %>
        <%= f.input :start_date, as: :string, label: "Dates", placeholder: "From", input_html: { data: { controller: "flatpickr", flatpickr_data_value: @flat.unavailable_start_dates.to_json } } %>
        <%= f.input :end_date, as: :string, label: '&nbsp;'.html_safe, placeholder: "To", input_html: { data: { controller: "flatpickr", flatpickr_data_value: @flat.unavailable_end_dates.to_json } } %>
        <%= f.submit "Book your flat", class: "app-button" %>
      <% end %>

        </div>
      </div>
      <br>
      <div>
        <a class="app-button-secondary" href="#">
          ♥ Add to wishlist
        </a>
      </div>
      <br>

    </div>
    </div>
</div>

<div class="container mb-3">
  <h2 class="text-center mb-4">Reviews</h2>
  <div class="row">
    <div class="col-md-7 reviews-section">
      <% if @reviews.any? %>
        <% @reviews.each do |review| %>
          <div class="list-group-item">
            <div class="d-flex justify-content-between">
              <h5 class="mb-1"><%= review.user.name %><span style="font-size:1rem"> - <%= review.user.email %></span></h5>
              <b><p>Rating: <%= review.rating %> / 5</p></b>
            </div>
            <p class="mb-1"><%= review.content %></p>
            <small class="text-muted">Reviewed on <%= review.created_at.strftime("%B %d, %Y") %></small>
          </div>
        <% end %>
      <% else %>
        <p class="text-muted">No reviews yet.</p>
      <% end %>
    </div>
    <div class="col-md-5">
      <%= render "reviews/review_form", flat: @flat, review: @review %>
    </div>
  </div>
</div>


<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<div class="py-5"></div>

app/views/layouts/_flat_card.html.erb
<div class="mb-3 flat-card">
  <%= link_to flat_path(flat), class: "card-link" do %>
    <%= image_tag(flat.poster_url, alt: "Flat image", class: "card-img-top") unless flat.poster_url.blank? %>
    <%= image_tag("https://th.bing.com/th/id/OIG4.tPvwVrEHahLe6Kjf4I0p?w=1024&h=1024&rs=1&pid=ImgDetMain", alt: "Default flat image", class: "card-img-top") if flat.poster_url.blank? %>
    <div class="card-body">
      <h5 class="card-title"><%= flat.name %></h5>
      <p class="card-text mb-1"><%= flat.address %></p>
      <p class="description"><%= "#{flat.description.truncate(35, separator: ' ')}" %></p>
      <span class="price"><b>€<%= flat.price %></b>/night</span>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAirbnbClone</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render partial: "/shared/custom_navbar" %>
    <p class="alert"><%= alert %></p>
    <%= render "shared/flashes" %>
    <%= yield %>
    <div class="my-1">&nbsp;</div>
    <%= render partial: "/shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row justify-content-center">
  <div class="col-sm-8 my-3 ">
    <%= form_with url: root_path, method: :get, class: "d-flex " do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control card-img-top",
            placeholder: "Search for a flat"
        %>
      <%= submit_tag "Search", name: "", class: "app-button" %>
    <% end %>
  </div>
</div>

<div class="home-card-container">
  <div class="row">
      <% if @flats.any? %>
        <% @flats.each do |flat| %>
        <div class="col-lg-2 col-md-4 mb-3 max-dimensions">
            <%= render partial: "layouts/flat_card", locals: { flat: flat } %>
        </div>
          <% end %>
        <% else %>
          <em>Sorry, no flats found.</em>
        <% end %>
  </div>
</div>
</div>

app/views/reviews/_review_form.html.erb
<div class = "review-container">
  <%= simple_form_for [flat, review], html: { class: 'd-flex flex-column justify-content-center' }  do |f| %>
      <%= f.input :content, as: :text, input_html: { class: "form-control" } %>
      <%= f.input :rating, as: :numeric, input_html: { min: 1, max: 5, class: "form-control" } %>
      <%= f.submit 'Submit Review', class: "app-button", style: "width:200px"%>
  <% end %>
</div>

app/views/shared/_custom_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
  <div><%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://www.creativefabrica.com/wp-content/uploads/2021/07/17/Bear-and-baby-cute-bears-logo-design-Graphics-14848876-1-1-580x387.jpg" , class: "logo-image"%>
    <h2 class="mb-0 ms-2">Bear BNB</h2>
    <% end %>
  </div>
  <div><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Add a Flat", new_flat_path, class: "nav-link" %>
          </li>
          <%# <li class="nav-item"> %>
            <%#= link_to "Your bookings", "#", class: "nav-link" %>
          <%# </li> %>
          <li class="nav-item dropdown">
            <%= image_tag "https://i.pinimg.com/736x/c0/74/9b/c0749b7cc401421662ae901ec8f9f660.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if current_user.owner? %>
                <%= link_to "Your flats", owner_flats_path, class: "dropdown-item" %>
              <% end %>
                <%= link_to "Your bookings", user_bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer fixed-bottom">
  <div class="footer-links">
    <a href="https://github.com/R0ad-to-code/rails-airbnb-clone"><i class="fab fa-github"></i> Visit our project on Github</a>
  </div>
  <div class="footer-copyright">
    This page is made with a lot of <i class="fas fa-mug-hot"></i> at BearBnB
  </div>
</div>